### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by adrielgorosito** [BrunoMollo/sysacad-automation#1]
Hello,

I used your script to register my subjects this monday 03/04/2024 but I thought it didn't work. Then I saw that this semester I'm going to study on the Tucuman regional. I really hope you have some good lawyers because you're going to broke.

Greetings from Santa Fe (Tucuman in the future)

**Comment by BrunoMollo** [comment]
Probaste reiniciando?

**Comment by BrunoMollo** [comment]
Me alegro que se haya solucionado este issue!! Cuando vuelvas de Tucuman trae alfajores
